# Generated by Django 3.2.5 on 2021-07-29 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0007_alter_photo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
