# Generated by Django 3.2.6 on 2021-08-18 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_alter_photo_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-is_featured', '-id'], 'verbose_name': 'Album', 'verbose_name_plural': 'Albums'},
        ),
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['id'], 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
    ]
