# Generated by Django 3.2.6 on 2021-08-28 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0010_auto_20210818_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='K4QPrrCxmqZA6ThxAfNpKg', max_length=255)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.album')),
            ],
        ),
    ]
