# Generated by Django 3.2.6 on 2021-08-28 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0011_albumtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='gallery',
        ),
        migrations.AddField(
            model_name='album',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='albumtoken',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='albumtoken',
            name='token',
            field=models.CharField(default='ijzV_n1N5uWLoPH5oxeQNw', max_length=255),
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
