# Generated by Django 3.2.6 on 2021-08-28 14:05

from django.db import migrations, models
import django.utils.timezone
import photos.models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20210828_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumtoken',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='albumtoken',
            name='expiry_date',
            field=models.DateTimeField(default=photos.models.get_default_token_expiry_date),
        ),
        migrations.AlterField(
            model_name='albumtoken',
            name='token',
            field=models.CharField(default='SRH94Lfrpe8qKbuwFN2Njw', max_length=255),
        ),
    ]
