# Generated by Django 3.2.6 on 2021-08-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0013_auto_20210828_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albumtoken',
            options={'verbose_name': 'Album Token', 'verbose_name_plural': 'Albums Tokens'},
        ),
        migrations.AlterField(
            model_name='albumtoken',
            name='token',
            field=models.CharField(default='3-oDSKGBR5EVOQlw6EyR_g', max_length=255),
        ),
    ]
