# Generated by Django 3.2.5 on 2021-07-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
    ]
