# Generated by Django 3.2.5 on 2021-07-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        ('blog', '0003_auto_20210725_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='photos.Photo'),
        ),
    ]
