# Generated by Django 3.2.5 on 2021-07-27 12:10

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210725_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='Image'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='Image')),
                ('is_featured', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
            ],
            options={
                'verbose_name': 'post_image',
                'verbose_name_plural': 'post_images',
            },
        ),
    ]
